apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-cleaner-<target cluster id>
  namespace: razee
spec:
  template:
    spec:
      containers:
      - name: cluster-remover
        image: <the image you built or jpapejr/razee-cluster-cleaner>
        env:
          - name: CLUSTER
            value: <target-cluster-id>
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: razeedash-secret
                key: mongo_url

      restartPolicy: Never
  backoffLimit: 1